/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        'leap-dark': '#334b46',
        'leap-gold': '#de9a49',
        'leap-tan': '#e0b788',
        'leap-olive': '#7c6b4b',
        'leap-maroon': '#803e2f',
        'leap-yellow': '#fae185',
        'leap-cream': '#f9ecb6',
        'leap-rust': '#b05a32',
        'leap-teal': '#4ab09a',
        'leap-blue': '#5ca0a8',
      },
    },
  },
  plugins: [
    function ({ addComponents }) {
      addComponents({
        '.leap-info-card': {
          'background': 'rgba(254, 250, 232, 0.86)',
          'border': '1px solid rgba(224, 183, 136, 0.26)',
          'border-radius': '0.875rem',
          'box-shadow': '0 8px 40px rgba(51, 75, 70, 0.09)',
        },
        '.leap-detail-icon-wrap': {
          'width': '46px',
          'height': '46px',
          'border-radius': '0.5625rem',
          'background': 'rgba(222, 154, 73, 0.1)',
          'border': '1px solid rgba(222, 154, 73, 0.22)',
          'display': 'flex',
          'align-items': 'center',
          'justify-content': 'center',
          'color': '#b05a32',
          'flex-shrink': '0',
          'transition': 'background 0.2s, transform 0.2s',
          '&:hover': {
            'background': 'rgba(222, 154, 73, 0.18)',
            'transform': 'scale(1.05)',
          },
        },
        '.leap-footer': {
          'background': 'linear-gradient(180deg, #1d2e28 0%, #141f1b 100%)',
          'border-top': '1px solid rgba(222, 154, 73, 0.14)',
        },
        '.leap-mobile-menu': {
          'background': 'linear-gradient(160deg, #0e1a0c 0%, #1c2d18 100%)',
        },
        '.leap-nav-inner': {
          'display': 'grid',
          'grid-template-columns': '1fr auto 1fr',
          'align-items': 'center',
          'max-width': '1280px',
          'margin': '0 auto',
          'padding': '0 1.5rem',
          'width': '100%',
        },
        '.leap-nav-logo': {
          'justify-self': 'start',
          'display': 'flex',
          'align-items': 'center',
        },
        '.leap-nav-center': {
          'justify-self': 'center',
          'display': 'flex',
          'align-items': 'center',
          'gap': '2rem',
        },
        '.leap-nav-right': {
          'justify-self': 'end',
          'display': 'flex',
          'align-items': 'center',
          'gap': '0.5rem',
        },
        '.leap-logo-hero': {
          'width': 'min(520px, 86vw)',
          'display': 'block',
          'margin': '0 auto',
          'mix-blend-mode': 'screen',
          'filter': 'drop-shadow(0 0 48px rgba(222, 154, 73, 0.65)) drop-shadow(0 0 96px rgba(222, 154, 73, 0.3)) drop-shadow(0 14px 36px rgba(0, 0, 0, 0.7))',
          'animation': 'heroFloat 5.5s ease-in-out infinite',
        },
        '.leap-admin-link': {
          'font-family': "'DM Sans', sans-serif",
          'font-weight': '700',
          'font-size': '0.78rem',
          'letter-spacing': '0.08em',
          'text-transform': 'uppercase',
          'color': '#de9a49',
          'transition': 'color 0.2s',
          'background': 'none',
          'border': 'none',
          'cursor': 'pointer',
          '&:hover': {
            'color': '#fae185',
          },
        },
        '.btn-leap-primary': {
          'font-family': "'DM Sans', sans-serif",
          'font-weight': '700',
          'font-size': '0.875rem',
          'letter-spacing': '0.07em',
          'text-transform': 'uppercase',
          'color': '#1a1008',
          'background': 'linear-gradient(135deg, #fae185 0%, #de9a49 55%, #c07830 100%)',
          'border': 'none',
          'border-radius': '0.375rem',
          'padding': '0.95rem 2.4rem',
          'box-shadow': 'inset 0 1px 0 rgba(255, 255, 255, 0.28), 0 6px 28px rgba(222, 154, 73, 0.5), 0 2px 8px rgba(0, 0, 0, 0.35)',
          'transition': 'filter 0.2s, transform 0.15s, box-shadow 0.2s',
          'cursor': 'pointer',
          'display': 'inline-flex',
          'align-items': 'center',
          'gap': '0.5rem',
          'text-decoration': 'none',
          'position': 'relative',
          'overflow': 'hidden',
          '&:hover': {
            'filter': 'brightness(1.1)',
            'transform': 'translateY(-2px)',
            'box-shadow': 'inset 0 1px 0 rgba(255, 255, 255, 0.28), 0 10px 36px rgba(222, 154, 73, 0.6), 0 3px 10px rgba(0, 0, 0, 0.4)',
          },
          '&:active': {
            'transform': 'translateY(0) scale(0.98)',
          },
        },
        '.leap-register-btn': {
          'font-family': "'DM Sans', sans-serif",
          'font-size': '0.78rem',
          'font-weight': '700',
          'letter-spacing': '0.09em',
          'text-transform': 'uppercase',
          'color': '#f9ecb6',
          'background': '#334b46',
          'border': 'none',
          'border-radius': '0.375rem',
          'padding': '0.82rem 1rem',
          'width': '100%',
          'display': 'flex',
          'align-items': 'center',
          'justify-content': 'center',
          'gap': '0.5rem',
          'text-decoration': 'none',
          'transition': 'background 0.2s, transform 0.15s, box-shadow 0.15s',
          'box-shadow': '0 3px 10px rgba(51, 75, 70, 0.2)',
          'position': 'relative',
          'overflow': 'hidden',
          '&:hover': {
            'background': '#803e2f',
            'color': '#fff',
            'transform': 'translateY(-1px)',
            'box-shadow': '0 6px 18px rgba(128, 62, 47, 0.32)',
          },
        },
        '.leap-class-card': {
          'background': 'rgba(254, 250, 232, 0.86)',
          'border': '1px solid rgba(224, 183, 136, 0.22)',
          'border-radius': '0.75rem',
          'overflow': 'hidden',
          'transition': 'transform 0.35s cubic-bezier(0.34, 1.2, 0.64, 1), box-shadow 0.35s ease, border-color 0.2s',
          'box-shadow': '0 2px 12px rgba(51, 75, 70, 0.06)',
          'position': 'relative',
          '&:hover': {
            'transform': 'translateY(-7px)',
            'box-shadow': '0 20px 56px rgba(51, 75, 70, 0.13), 0 6px 16px rgba(222, 154, 73, 0.1)',
            'border-color': 'rgba(224, 183, 136, 0.52)',
          },
        },
      })
    },
  ],
}

